FROM ubuntu:disco

RUN apt-get update
RUN apt-get install -y libcereal-dev libzstd-dev libboost-filesystem-dev libboost-system-dev libbotan-2-dev libpqxx-dev ninja-build meson build-essential ca-certificates

