FROM ubuntu:disco

RUN apt-get update
RUN apt-get install -y libssl-dev libcereal-dev libzstd-dev libboost-filesystem-dev libboost-system-dev qtbase5-dev ninja-build meson build-essential

# ca-certificates

